### ISSUE TITLE
Slot outside the autosuggest_results div

### ISSUE THREAD

**Issue by vlledo** [darrenjennings/vue-autosuggest#162]
First of all, thanks for your amazing work, the component works like a charm. I'm using the **2.0.4** version and I'm trying to render a link to see more results when the amount of them exceeds the limit that I've configured. For this purpose, I've used the `after-suggestions` slot, and it works properly.

The problem comes when I set a `max-height` for the results container:

```css
.autosuggest__results {
  max-height: 500px
  overflow: scroll;
}
```

The `after-suggestions` slot is rendered after the `<ul>` **but inside** the `<div class="autosuggest__results">` so is not possible to make it visible (without scrolling) when the results exceed the `max-height` configured. I've tried to add the `max-height` and `overflow` properties to the `<ul>` directly, but this breaks the keyboard navigation. I would like to be able to have a `See more` link always visible (when there are more available results) without scrolling the list.

Here you could see [an example in codebox](https://codesandbox.io/s/vueautosuggest-20-base-vxuz7).

So, the question is: Is there a way to position a slot just after the `autosuggest_results` container? If not, it would be possible to move the existing `after-suggestions` slot outside it? Do you think that it makes sense?

Thanks in advance!

**Comment by darrenjennings** [comment]
this is more of a css question. Hadn't had to do this before, but looks like you can get it by moving the overflow to the `ul` and adding some positioning.

```css
.autosuggest__results {
  position: relative;
}

ul {
  max-height: 120px;
  overflow: scroll;
}

.autosuggest__see-more {
  position: absolute;
  top: 120px; /* height of results */ 
}
```
