### ISSUE TITLE
[before|after]-input no longer adjacent to input

### ISSUE THREAD

**Issue by jenglish404** [darrenjennings/vue-autosuggest#205]
- `vue-autosuggest` version: 2.2.0
- `node` version: 12.18.1
- `npm` (or `yarn`) version: 6.14.8

Problem description:

In the [most recent change](https://github.com/darrenjennings/vue-autosuggest/commit/07dabec39e2254168df77ffdc60595b84f1742c0#diff-7f218440d6b2a14bebc64edbf09038cc), it looks like a div was added as a wrapper around the input:
```html
<slot name="before-input" /><div
      role="combobox"
      :aria-expanded="isOpen ? 'true' : 'false'"
      aria-haspopup="listbox"
      :aria-owns="`${componentAttrIdAutosuggest}-${componentAttrPrefix}__results`"
    ><input
      :type="internal_inputProps.type"
      :value="internalValue"
      :autocomplete="internal_inputProps.autocomplete"
      :class="[isOpen ? `${componentAttrPrefix}__input--open` : '', internal_inputProps['class']]"
      v-bind="internal_inputProps"
      aria-autocomplete="list"
      :aria-activedescendant="isOpen && currentIndex !== null ? `${componentAttrPrefix}__results-item--${currentIndex}` : ''"
      :aria-controls="`${componentAttrIdAutosuggest}-${componentAttrPrefix}__results`"
      @input="inputHandler"
      @keydown="handleKeyStroke"
      v-on="listeners"
    ></div><slot name="after-input" />
```

The end result is that the `[before|after]-input` slots are now before|after the div, not the input. We were using the `after-input` slot along with some Sass that relies on the label being adjacent to the input (`input + label`):
```scss
input[type='text'] {
  & + label {
      font-size: 12px;
      position: absolute;
      top: -10px;
      left: 14px;
      opacity: 0;
      color: transparent;
      @include transition-all;
  }
  
  // input focus
  &:focus {
    &::placeholder {
        color: transparent;
      }
  }

  &:not(:placeholder-shown) {
      & + label {
        top: -17px;
        left: 5px;
        opacity: 1;
      }

      &::placeholder {
        color: transparent;
      }
    }
}
```
Here's what that looks like in action (label floats above input when input receives focus):
![floating-label](https://user-images.githubusercontent.com/35153209/93250506-c3ec3f80-f747-11ea-904d-920e9d403bfc.gif)

Since the `after-input` slot is no longer adjacent to the input, it breaks this styling. I tried working around this, but there's no sibling-of-parent CSS selector (that I'm aware of).

Suggested solution:

### Option 1
Revert the change (remove the div wrapper). I see that some of the aria attributes have been shuffled around, so if it needs to be this way then...
### Option 2
Move the `[before|after]-input` slots inside the wrapper so that they're once again adjacent to the input.

I'm happy to make the change and open a PR if that helps.
